[contest]
name = "test"
description = "Test"
token_mode = "infinite"

[[contest.users]]
username = "u1"
password = "p1"

[contest-config]
languages = ["C11 / gcc", "C++17 / g++", "C++14 / g++"]

[contest-config.mapping]
"C11 / gcc" = [".c"]
"C++17 / g++" = [".cpp", ".cc", ".cxx", ".c++", ".C"]
"C++14 / g++" = [".cpp", ".cc", ".cxx", ".c++", ".C"]

[task_template]
infile = ""
outfile = ""
task_type = "Batch"
score_mode = "max_subtask" # 2017~
token_mode = "disabled"
score_type = "GroupMin"
score_type_parameters = ""
time_limit = 15
memory_limit = 1024
min_submission_interval = 120
min_user_test_interval = 120
primary_language = "zh_TW"

[[tasks]]
name = "brackets"
title = "括號問題"
time_limit = 1.0
  [tasks.inclusive_tests]
  3 = ["0", "1", "2"]

[[tasks]]
name = "postoffice"
title = "郵局"
time_limit = 2.0
  [tasks.inclusive_tests]
  2 = ["0", "1"]
  4 = ["0", "3"]
  5 = ["0", "1", "2", "3", "4"]

[[tasks]]
name = "ev"
title = "電動車充電規劃問題"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1"]
  4 = ["0", "1", "2", "3"]

[[tasks]]
name = "chomp"
title = "Chomp!"
time_limit = 1.0
  [tasks.inclusive_tests]
  3 = ["0", "1", "2"]

[[tasks]]
name = "decode"
title = "解碼密鑰"
time_limit = 1.0
  [tasks.inclusive_tests]
  3 = ["2"]
  4 = ["0", "1", "2", "3"]

[[tasks]]
name = "datacenter"
title = "資料中心"
time_limit = 4.0
  [tasks.inclusive_tests]
  3 = ["1", "2"]
  5 = ["0", "1", "2", "3", "4"]

[[tasks]]
name = "connections"
title = "神聖的連線儀式"
time_limit = 3.0
  [tasks.inclusive_tests]
  2 = ["0", "1"]
  3 = ["0"]
  4 = ["0", "1"]
  5 = ["0", "2", "3"]
  6 = ["0", "1", "2", "3", "4", "5"]
  7 = ["0", "1", "2", "3", "4", "5", "6"]

[[tasks]]
name = "diameter"
title = "融合圖的直徑"
time_limit = 1.0
  [tasks.inclusive_tests]
  3 = ["0", "1"]
  4 = ["0", "1", "2", "3"]

[[tasks]]
name = "parade"
title = "彩色遊行"
time_limit = 6.0
  [tasks.inclusive_tests]
  2 = ["0"]
  4 = ["0", "1", "2", "3"]
